# Generated by Django 2.2.2 on 2019-06-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190617_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_day',
            new_name='pub_date',
        ),
    ]
